services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: notification_rabbit_mq
    networks:
      - notification_net
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      
    ports:
      - "5672:5672"
      - "15672:15672"
      
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 10s
      
  email_sender:
    extends:
      service: email_sender
      file: email-service.yml

    networks:
      - notification_net
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  notification_net:
    
volumes:
  rabbitmq_data: