services:
  email_sender:
    image: wallghost/email-sender-subscriber:latest
    container_name: email_sender
    env_file:
      - ./.env
    environment:
      Smtp__Host: ${SMTP_HOST}
      Smtp__Port: ${SMTP_PORT}
      Smtp__User: ${SMTP_USER}
      Smtp__Password: ${SMTP_PASSWORD}
      Smtp__FromEmail: ${SMTP_FROM_EMAIL}
      Smtp__FromName: ${SMTP_FROM_NAME}
      RabbitMq__HostName: rabbitmq
      RabbitMq__Port: ${RABBITMQ_PORT}
      RabbitMq__UserName: ${RABBITMQ_USER}
      RabbitMq__Password: ${RABBITMQ_PASSWORD}
      RabbitMq__QueueName: ${RABBITMQ_NOTIFICATION_EMAIL_SENDER_QUEUE_NAME}
      RabbitMq__VirtualHost: ${RABBITMQ_NOTIFICATION_EMAIL_SENDER_VIRTUAL_HOST}
      RabbitMq__PrefetchCount: ${RABBITMQ_NOTIFICATION_EMAIL_SENDER_PREFECTH_COUNT}
      RabbitMq__QueueMessageTtl: ${RABBITMQ_NOTIFICATION_EMAIL_SENDER_MESSAGE_TTL}
      RabbitMq__DeadLetterExchangeName: ${RABBITMQ_NOTIFICATION_EMAIL_SENDER_DEAD_LETTER_EXCHANGE}